[package]
name = "pingsix"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.7.1"
async-trait = "0.1.83"
base64 = "0.22.1"
bytes = "1.8.0"
dashmap = "6.1.0"
env_logger = { version = "0.11.5", features = ["unstable-kv"] }
etcd-client = "0.14.0"
futures = "0.3.31"
hickory-resolver = "0.24.1"
http = "1.1.0"
ipnetwork = { version = "0.20.0", features = ["serde"] }
jsonwebtoken = "9.3.1"
log = { version = "0.4.22", features = ["kv"] }
matchit = "0.8.5"
once_cell = "1.20.2"
pingora = { version = "0.4", features = ["openssl", "sentry"] }
pingora-core = "0.4.0"
pingora-error = "0.4.0"
pingora-http = "0.4.0"
pingora-limits = "0.4.0"
pingora-load-balancing = "0.4.0"
pingora-proxy = "0.4.0"
pingora-runtime = "0.4.0"
prometheus = "0.13.4"
rand = "0.8"
regex = "1.11.1"
sentry = "0.26"
serde = { version = "1.0.197", features = ["derive"] }
serde-transcode = "1.1.1"
serde_json = "1.0.133"
serde_yaml = "0.9.34"
tokio = { version = "1.41.1", features = ["fs"] }
uuid = { version = "1.16.0", features = ["v4"] }
validator = { version = "0.18.1", features = ["derive"] }

# TODO: remove when pingora releases a fix https://github.com/cloudflare/pingora/issues/568
[patch.crates-io]
sfv = { git = "https://github.com/undef1nd/sfv.git", tag = "v0.9.4" }
