# pingora config example from https://github.com/cloudflare/pingora/blob/main/docs/user_guide/conf.md
pingora:
  version: 1
  threads: 2
  pid_file: /run/pingora.pid
  upgrade_sock: /tmp/pingora_upgrade.sock
  user: nobody
  group: webusers

pingsix:
  # listener on TCP or TLS
  listeners:
    - address: 0.0.0.0:8080
    # - address: "[::1]:443"
    #   tls:
    #     cert_path: /etc/ssl/server.crt
    #     key_path: /etc/ssl/server.key
    #   offer_h2: true
  
  # etcd:
  #   host:
  #     - "http://192.168.2.141:2379"
  #   prefix: /apisix

  # admin:
  #   address: "0.0.0.0:9181"
  #   api_key: pingsix

  prometheus:
    address: 0.0.0.0:9091

  sentry:
    dsn: https://1234567890@sentry.io/123456

# api routes example for https://apisix.apache.org/docs/apisix/admin-api/#route
# Here is a complete example, which is a subset of routes from the apisix docs. The fields not mentioned here indicate that pingsix does not support them.
# The fields in the following comments are all optional parameters.
routes:
  - id: 1
    uri: /
    # uris: ["/","/test"]
    host: www.baidu.com
    # hosts: ["www.baidu.com","www.taobao.com"]
    # methods: ["GET", "POST"]
    # timeout:
    #   connect: 2
    #   send: 3
    #   read: 5
    # priority: 10
    upstream: # Field description https://apisix.apache.org/docs/apisix/admin-api/#upstream
      # id: 1
      # retries: 2
      # retry_timeout: 10
      nodes:
        "www.baidu.com": 1
      type: roundrobin # supported types: roundrobin, random, fnv, ketama
      # timeout:
      #   connect: 2
      #   send: 3
      #   read: 5
      checks: # Field description https://apisix.apache.org/docs/apisix/tutorials/health-check/
        active: # only support active check
          type: https
          timeout: 1
          host: www.baidu.com
          http_path: /
          # port: 8443
          https_verify_certificate: true
          req_headers: ["User-Agent: curl/7.29.0"]
          healthy:
            interval: 5
            http_statuses: [200, 201]
            successes: 2
          unhealthy:
            http_failures: 5
            tcp_failures: 2
      hash_on: vars # supported types: vars, cookie, head
      key: uri
      pass_host: rewrite
      upstream_host: www.baidu.com
      scheme: https
  - id: 2
    uri: /
    host: www.taobao.com
    upstream_id: 1
  - id: 3
    uri: /
    service_id: 1
  - id: 4
    uri: /
    host: www.163.com
    service_id: 2
  - id: 5
    uri: /echo
    host: www.163.com
    service_id: 2
    plugins:
      echo:
        body: "Hello world!"
        headers:
          X-TEST: demo

upstreams:
  - id: 1
    nodes:
      "www.taobao.com": 1
    type: roundrobin
    pass_host: rewrite
    upstream_host: www.taobao.com
    scheme: http
  - id: 2
    nodes:
      "www.qq.com": 1
    type: roundrobin
    scheme: http

services:
  - id: 1
    hosts: ["www.qq.com"]
    upstream_id: 2
  - id: 2
    upstream:
      nodes:
        "www.163.com": 1
      type: roundrobin
      scheme: http
    plugins:
      limit-count:
        key_type: head
        key: Host
        time_window: 1
        count: 1
        rejected_code: 429
        rejected_msg: "Pleas slow down!"

global_rules:
  - id: 1
    plugins:
      prometheus: {}
